name: fifa
channels:
  - pytorch-lts
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - anyio=3.5.0=py38h578d9bd_0
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_2
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - cryptography=35.0.0=py38ha5dfef3_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py38h578d9bd_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=5.5.5=py38hd0cf306_0
  - ipython=7.31.1=py38h578d9bd_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jedi=0.18.1=py38h578d9bd_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.1.1=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38h578d9bd_1
  - jupyter_server=1.13.3=pyhd8ed1ab_0
  - jupyterlab=3.2.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1004
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - nbclassic=0.3.5=pyhd8ed1ab_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.0=py38h578d9bd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.4.7=pyha770c72_0
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.17.0.1=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py38h5aabda8_0
  - pip=21.2.4=py38h06a4308_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.24=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h578d9bd_4
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.2=py3.8_cuda11.1_cudnn8.0.5_0
  - pytz=2021.3=pyhd8ed1ab_0
  - pyzmq=19.0.2=py38ha71036d_2
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sniffio=1.2.0=py38h578d9bd_2
  - sqlite=3.37.0=hc218d9a_0
  - terminado=0.12.1=py38h578d9bd_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - timm=0.4.12=pyhd8ed1ab_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.8.2=py38
  - torchvision=0.9.2=py38_cu111
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38h578d9bd_1
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - alabaster==0.7.12
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - autopep8==1.6.0
    - beautifulsoup4==4.10.0
    - cachetools==4.2.4
    - cupy==10.3.1
    - cupy-cuda112==10.3.1
    - cycler==0.11.0
    - decorator==4.4.2
    - docutils==0.17.1
    - einops==0.4.1
    - et-xmlfile==1.1.0
    - fastrlock==0.8
    - filelock==3.6.0
    - flake8==4.0.1
    - flatbuffers==2.0
    - fonttools==4.28.5
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - gast==0.5.3
    - gdown==4.3.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - h5py==3.6.0
    - imageio==2.16.0
    - imageio-ffmpeg==0.4.5
    - imagesize==1.3.0
    - iniconfig==1.1.1
    - ipdb==0.13.9
    - joblib==1.1.0
    - jsonpatch==1.32
    - jsonpointer==2.2
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==13.0.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mccabe==0.6.1
    - moviepy==1.0.3
    - multidict==6.0.2
    - networkx==2.6.3
    - ninja==1.10.2.3
    - oauthlib==3.1.1
    - opencv-python==4.5.5.62
    - openpyxl==3.0.9
    - opt-einsum==3.3.0
    - pandas==1.4.1
    - pluggy==1.0.0
    - proglog==0.1.9
    - protobuf==3.19.3
    - ptflops==0.6.8
    - py==1.11.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pycodestyle==2.8.0
    - pydeprecate==0.3.2
    - pyflakes==2.4.0
    - pytest==6.2.5
    - pytorch-fid==0.2.1
    - pytorch-lightning==1.6.0
    - pywavelets==1.2.0
    - pyyaml==6.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - segformer-pytorch==0.0.6
    - sklearn==0.0
    - snowballstemmer==2.2.0
    - soupsieve==2.3.1
    - sphinx==4.4.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5
    - tensorflow==2.8.0
    - tensorflow-hub==0.12.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.0.0
    - tifffile==2022.2.9
    - toml==0.10.2
    - torchfile==0.1.0
    - torchinfo==1.6.3
    - torchmetrics==0.7.3
    - torchnet==0.0.4
    - tqdm==4.62.3
    - typing-extensions==4.1.1
    - visdom==0.1.8.9
    - werkzeug==2.0.2
    - wrapt==1.14.0
    - yarl==1.7.2